# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Mouse move with variable speed

compatible: "zmk,behavior-mv"

properties:
  "#binding-cells":
    type: int
    required: true
    const: 2

binding-cells:
  - param1
  - param2