# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Toggle switch for kp2 behavior

compatible: "zmk,behavior-toggle"

properties:
  "#binding-cells":
    type: int
    required: true
    const: 0