compatible: "zmk,behavior-speed-modifier"
description: "Hold to reduce mouse speed of a dynamic-mouse-move instance"
properties:
  target:
    type: phandle
    required: true
    description: "Phandle to dynamic_mouse_move node"
  slow_factor:
    type: int
    required: true
    description: "Speed multiplier while key is held"
  "#binding-cells":
    type: int
    const: 0