description: two axis move
compatible: "zmk,behavior-two-axis-move"
properties:
  x-input-code:
    type: int
    required: true
  y-input-code:
    type: int
    required: true
  trigger-period-ms:
    type: int
    default: 16
  delay-ms:
    type: int
  time-to-max-speed-ms:
    type: int
    required: true
  acceleration-exponent:
    type: int
    default: 1
  "#binding-cells":
    type: int
    required: true
    const: 2
binding-cells:
  - param1
  - param2