# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Toggle speed of a dynamic mouse move behavior

compatible: "zmk,behavior-speed-change"

include: base.yaml

properties:
  target:
    type: phandle
    required: true
    description: Reference to the dynamic mouse move device to control