# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Dynamic dual-speed mouse movement behavior

compatible: "zmk,behavior-dynamic-mouse-move"

properties:
  x-input-code:
    type: int
    required: true
  y-input-code:
    type: int
    required: true
  trigger-period-ms:
    type: int
    default: 8
  delay-ms:
    type: int
  time-to-max-speed-ms:
    type: int
    required: true
  acceleration-exponent:
    type: int
    default: 1

binding-cells:
  - param1
  - param2