# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Toggle speed slot for dynamic mouse move

compatible: "zmk,behavior-speed-change"

include: base.yaml

properties:
  target:
    type: phandle
    required: true